package com.ithirteeng.features.collections.presentation

const val COLLECTION_MAIN_VIEW_MODEL = "COLLECTION_MAIN"
const val COLLECTION_INFO_VIEW_MODEL = "COLLECTION_INFO"
const val COLLECTION_CREATE_VIEW_MODEL = "COLLECTION_CREATE"
const val COLLECTION_CHANGE_VIEW_MODEL = "COLLECTION_CHANGE"
const val CHOOSE_ICON_VIEW_MODEL = "CHOOSE_ICON"